-- Cupom semanal via jogo da memória (MVP)
-- Rode no SQL Editor do Supabase

create table if not exists public.coupons (
  code text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  label text,
  discount_type text not null check (discount_type in ('percent','shipping_reduced','fixed_min')),
  discount_value numeric(10,2) not null default 0,
  min_order_value numeric(10,2) not null default 0,
  active boolean not null default true,
  max_uses integer not null default 1,
  used_count integer not null default 0,
  source text,
  week_key text,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_coupons_user_id on public.coupons(user_id);
create index if not exists idx_coupons_week_key on public.coupons(week_key);

create table if not exists public.coupon_game_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_key text not null,
  played_at timestamptz not null default now(),
  won boolean not null default false,
  score integer,
  attempts integer,
  duration_ms integer,
  reward_type text,
  reward_label text,
  coupon_code text references public.coupons(code) on delete set null,
  unique (user_id, week_key)
);

create index if not exists idx_coupon_game_sessions_user_week on public.coupon_game_sessions(user_id, week_key);

create table if not exists public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_code text not null references public.coupons(code) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  order_id uuid,
  discount_amount numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.coupons enable row level security;
alter table public.coupon_game_sessions enable row level security;
alter table public.coupon_redemptions enable row level security;

-- Usuário vê apenas seus próprios registros
create policy if not exists "coupons_select_own" on public.coupons
for select to authenticated using (auth.uid() = user_id);

create policy if not exists "coupon_game_sessions_select_own" on public.coupon_game_sessions
for select to authenticated using (auth.uid() = user_id);

create policy if not exists "coupon_redemptions_select_own" on public.coupon_redemptions
for select to authenticated using (auth.uid() = user_id);

-- Inserções/updates são feitas pelo backend com service role (bypass RLS)
